// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHh8Emtdz5Uch3Yuk6i2A6INAoeWbbEk0',
    appId: '1:604397227822:web:58e7792488f61c82a334bf',
    messagingSenderId: '604397227822',
    projectId: 'digimcq',
    authDomain: 'digimcq.firebaseapp.com',
    storageBucket: 'digimcq.appspot.com',
    measurementId: 'G-RNC69D1QJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChZWUiJ2TSu2lXEaBFiV6u9VhElnvm2yU',
    appId: '1:604397227822:android:269394b07a95051ba334bf',
    messagingSenderId: '604397227822',
    projectId: 'digimcq',
    storageBucket: 'digimcq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI6TQahVoNxwlSqHnHtBfe7S2n6DRstOA',
    appId: '1:604397227822:ios:e3be37f8d4ebf9dda334bf',
    messagingSenderId: '604397227822',
    projectId: 'digimcq',
    storageBucket: 'digimcq.appspot.com',
    iosClientId: '604397227822-vv98oaseibs9u2b6a9hoo94ppoie3e8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.digimcq',
  );
}
